version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: api-cadastro-clientes
    depends_on:
      - mongo
      - redis-cache
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
      - .env:/app/.env

  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - 6379:6379
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}

