import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';

export type ClientDocument = HydratedDocument<ClientModel>;

@Schema({
  timestamps: true,
  toJSON: {
    transform: function (doc, ret) {
      delete ret.address._id;
      return {
        id: ret._id,
        name: ret.name,
        email: ret.email,
        phone: ret.phone,
        address: ret.address,
      };
    },
  },
})
export class ClientModel {
  // Id will be unique and generated by MongoDB UUID
  @Prop({ required: true, unique: true, default: () => new Types.ObjectId() })
  id: string;

  @Prop({ required: true })
  name: string;

  @Prop({ required: true })
  phone: string;

  @Prop({ required: true, unique: true })
  email: string;

  @Prop({
    type: {
      cep: String,
      state: String,
      city: String,
      neighborhood: String,
      street: String,
    },
    required: true,
  })
  address: {
    cep: string;
    state: string;
    city: string;
    neighborhood: string;
    street: string;
  };
}

export const ClientSchema = SchemaFactory.createForClass(ClientModel);
